# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeartRateProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

  # Pods for HeartRateProject
pod 'Charts'
pod 'FontAwesome.swift','1.3.2'
pod 'Firebase/Core'
pod 'Firebase/Database'

end

